
import React, { useState } from 'react';
import { supabase } from '../supabaseClient';
// Added UserRole to the imports
import { User, Campus, UserRole } from '../types';

const Reports: React.FC<{ user: User }> = ({ user }) => {
  const [reportType, setReportType] = useState('summary');
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [loading, setLoading] = useState(false);
  const [reportData, setReportData] = useState<any[]>([]);
  const [hasGenerated, setHasGenerated] = useState(false);

  const generateReport = async () => {
    setLoading(true);
    setHasGenerated(true);
    try {
      const startOfMonth = `${month}-01`;
      const endOfMonth = `${month}-31`; // Simplified, Supabase handles range well

      let query = supabase
        .from('attendance_records')
        .select('*, employees!inner(name, campus, id, designation)')
        .gte('date', startOfMonth)
        .lte('date', endOfMonth)
        .order('date', { ascending: false });

      if (user.role === UserRole.MUDEER) {
        query = query.eq('employees.campus', user.campus);
      }

      const { data, error } = await query;
      if (error) throw error;
      setReportData(data || []);
    } catch (err: any) {
      alert("Report generation failed: " + err.message);
    } finally {
      setLoading(false);
    }
  };

  const exportPDF = () => {
    const { jsPDF } = (window as any).jspdf;
    const doc = new jsPDF('p', 'mm', 'a4');
    
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Attendance Audit Report', 15, 20);
    
    doc.setFontSize(10);
    doc.text(`Fiqh Academy Management System | ${month}`, 15, 28);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Generated by: ${user.name}`, 15, 50);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 15, 55);

    const rows = reportData.map((r, i) => [
      r.date,
      r.employees?.name || 'N/A',
      r.employees?.campus?.toUpperCase() || '--',
      r.time_in || '--:--',
      r.time_out || '--:--',
      r.status.toUpperCase(),
      r.late_hours > 0 ? `${r.late_hours}h` : '0'
    ]);

    (doc as any).autoTable({
      head: [['Date', 'Staff Name', 'Campus', 'In', 'Out', 'Status', 'Late']],
      body: rows,
      startY: 65,
      theme: 'striped',
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold' },
      styles: { fontSize: 8 },
      columnStyles: {
        5: { fontStyle: 'bold' }
      }
    });

    doc.save(`AMS_Audit_${month}.pdf`);
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-700">
      <div className="bg-white p-10 rounded-[2.5rem] shadow-sm border border-slate-100">
        <div className="mb-10">
          <h2 className="text-3xl font-black text-slate-800 tracking-tight">Audit Console</h2>
          <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] mt-2">Generate Official Records</p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">REPORT SCHEMA</label>
            <select 
              className="w-full px-6 py-4 bg-slate-50 border border-slate-100 rounded-2xl outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 font-bold text-slate-700 shadow-inner cursor-pointer"
              value={reportType}
              onChange={e => setReportType(e.target.value)}
            >
              <option value="summary">Monthly Presence Summary</option>
              <option value="late">Late Arrival Audit</option>
              <option value="overtime">Overtime Analysis</option>
              <option value="leave">Allocated Leave Balance</option>
            </select>
          </div>
          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">FISCAL PERIOD</label>
            <input 
              type="month" 
              className="w-full px-6 py-4 bg-slate-50 border border-slate-100 rounded-2xl outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 font-black text-slate-700 shadow-inner" 
              value={month}
              onChange={(e) => setMonth(e.target.value)}
            />
          </div>
          <div className="flex items-end gap-3">
            <button 
              onClick={generateReport}
              disabled={loading}
              className="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-black py-4 rounded-2xl shadow-2xl shadow-blue-200 transition-all flex items-center justify-center gap-3 active:scale-95 text-[10px] uppercase tracking-widest"
            >
              {loading ? <i className="fas fa-circle-notch fa-spin"></i> : <i className="fas fa-cog"></i>}
              EXECUTE
            </button>
            <button 
              disabled={reportData.length === 0 || loading}
              onClick={exportPDF}
              className="flex-1 bg-slate-900 hover:bg-black text-white font-black py-4 rounded-2xl shadow-2xl shadow-slate-200 transition-all flex items-center justify-center gap-3 active:scale-95 text-[10px] uppercase tracking-widest disabled:opacity-20"
            >
              <i className="fas fa-file-export"></i>
              EXPORT
            </button>
          </div>
        </div>
      </div>

      {hasGenerated && (
        <div className="bg-white rounded-[2.5rem] shadow-sm border border-slate-100 overflow-hidden">
          <div className="p-8 border-b border-slate-50 flex justify-between items-center">
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
              Found <span className="text-blue-600">{reportData.length}</span> entries for <span className="text-blue-600">{month}</span>
            </p>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left">
               <thead>
                 <tr className="text-[10px] font-black text-slate-300 uppercase tracking-widest bg-slate-50/50">
                   <th className="px-10 py-6">Timestamp</th>
                   <th className="px-10 py-6">Staff Profile</th>
                   <th className="px-10 py-6">Check In/Out</th>
                   <th className="px-10 py-6">Campus</th>
                   <th className="px-10 py-6">Audit Status</th>
                 </tr>
               </thead>
               <tbody className="divide-y divide-slate-50">
                 {loading ? (
                   <tr><td colSpan={5} className="text-center py-32"><div className="animate-spin h-10 w-10 border-4 border-blue-600 border-t-transparent rounded-full mx-auto"></div></td></tr>
                 ) : reportData.length === 0 ? (
                   <tr><td colSpan={5} className="text-center py-32 text-slate-300 font-black uppercase text-[10px] tracking-widest">No matching logs found in period</td></tr>
                 ) : reportData.map((r, i) => (
                   <tr key={i} className="hover:bg-slate-50/50 transition-colors">
                     <td className="px-10 py-6 font-mono text-xs font-black text-slate-400">{r.date}</td>
                     <td className="px-10 py-6">
                       <p className="text-sm font-black text-slate-800 tracking-tight">{r.employees?.name}</p>
                       <p className="text-[9px] font-black text-slate-300 uppercase">{r.employees?.designation}</p>
                     </td>
                     <td className="px-10 py-6 text-xs font-black text-slate-600 font-mono">
                       <span className="text-emerald-500">{r.time_in || 'N/A'}</span> / <span className="text-rose-500">{r.time_out || 'N/A'}</span>
                     </td>
                     <td className="px-10 py-6">
                        <span className="text-[9px] font-black uppercase text-slate-400">{r.employees?.campus}</span>
                     </td>
                     <td className="px-10 py-6">
                       <span className={`px-4 py-1.5 rounded-full text-[9px] font-black uppercase shadow-sm ${
                          r.status === 'present' ? 'bg-emerald-100 text-emerald-700' : 'bg-rose-100 text-rose-700'
                       }`}>
                         {r.status}
                       </span>
                     </td>
                   </tr>
                 ))}
               </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
};

export default Reports;
